server:
  port: 8761


eureka:
  instance:
    hostname: ${springboot.app.name:registry}
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    peer-node-read-timeout-ms: 120000

spring:
  application:
    name: ${springboot.app.name:registry}