server:
  port: 1111

spring:
  application:
    name: ${springboot.app.name:word-articles}
  cloud:
    service-registry:
      auto-registration:
        fail-fast: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1